@startuml
'https://plantuml.com/use-case-diagram
left to right direction

(履约订单) as (FulfillOrder)

MQ --> (FulfillOrder)

FulfillOrder -->(更新skuItem信息)
FulfillOrder -->(发货回传三方系统)
FulfillOrder -->(通知其他系统)
@enduml