@startuml
'https://plantuml.com/use-case-diagram
left to right direction

(订单履约) as (FulfillOrder)
(订单拆单) as splitOrder
(订单分仓) as dispatch
MQ --> (FulfillOrder)

FulfillOrder --> splitOrder
FulfillOrder -->dispatch
FulfillOrder -->(通知仓库发货)

dispatch ..> (位置就近原则)
dispatch ..> (库存充足优先原则)
dispatch ..> (成本最优原则)
dispatch ..> (商品属性原则)
dispatch ..> (订单优先级原则)
dispatch ..> (仓库处理能力原则)
@enduml